services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    ports:
      - "8082:8081"
    environment:
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - SERVICE_URL=${SERVICE_URL}
      - SERVER_PORT=${SERVER_PORT}
    env_file:
      - .env
    networks:
      - app-network
networks:
  app-network:
    external: true